const en = {
  login: { title: 'Login', username: 'Username', password: 'Password', loginBtn: 'Login', remember: 'Remember me', forgot: 'Forgot password?', error: 'Invalid username or password', setup: 'Setup Password', setupBtn: 'Setup', setupLink: 'Set up password for the first time', newPassword: 'New Password', confirmPassword: 'Confirm Password', accountName: 'Account Name', backToLogin: 'Back to Login', lockoutTitle: 'Locked', lockoutMsg: 'Too many failed attempts. Please try again later.', errorRequired: 'Please enter username', errorPasswordLength: 'Password must be at least 4 characters', errorPasswordMatch: 'Passwords do not match', errorSetup: 'Setup error. Please try again.', errorAuth: 'Authentication error. Please try again.', errorTooMany: 'Too many failed attempts. Please try again in 30 minutes.', errorAttempt: 'Invalid username or password ({n} attempts left)', showPassword: 'Show password', hidePassword: 'Hide password', tagline: 'Track your work time — Visual & Efficient', feature1: 'Analyze JIRA data with 5+ visual charts', feature2: 'Smart label management, auto-classify tasks', feature3: 'Save & compare analysis history over time', feature4: 'Desktop app — No browser needed' },
  sidebar: { overview: 'Overview', data: 'Data', burndown: 'Burndown', monthCompare: 'Month Compare', report: 'Report', ot: 'OT & Leave', labels: 'Labels', history: 'History', weeklyPlanner: 'Work Plan', weeklyTasks: 'Weekly Tasks', createTask: 'Create Task', expand: 'Expand', collapse: 'Collapse' },
  dashboard: { title: 'JIRA Dashboard', noData: 'No data', backToTop: 'Back to top', lastUpdate: 'Last updated:', updating: 'Updating...', source: 'Source:', jiraApi: 'JIRA API', htmlExport: 'HTML Export', historySource: 'History', csvSource: 'File', refreshError: 'Auto-refresh failed:', manualRefreshError: 'Refresh failed:', noTasksFound: 'No tasks found.', taskCount: 'tasks', logged: 'logged', changeProject: 'Change Project', manualRefresh: 'Manual refresh', otPrefix: 'OT: +', leavePrefix: 'Leave: -', overdueMore: 'and', otherTask: 'other tasks' },
  stats: { totalTasks: 'Total Tasks', totalHours: 'Total Hours Logged', totalEstimate: 'Total Estimate', avgPerTask: 'Avg Per Task', effort: 'Effort', effortMonth: 'Month Effort', effortAvg: 'Avg Effort', overview: 'Overview', currentMonth: 'Current Month', allStatuses: 'all statuses', above: '✅ Above', below: '⚠️ Below', sufficient: '✅ Sufficient', avgDetail: 'Average ({n} months)', effortWarning: '⚠️ Effort > 1 — check if all tasks are logged' },
  filter: { sprint: 'Sprint', component: 'Component', assignee: 'Assignee', fromDate: 'From', toDate: 'To', reset: 'Clear Filters', all: 'All', allSprints: 'All Sprints', allComponents: 'All Components', clearAll: 'Clear all filters' },
  table: { key: 'Issue Key', summary: 'Summary', component: 'Component', sprint: 'Sprint', assignee: 'Assignee', hoursLogged: 'Hours Logged', hoursEstimate: 'Estimate', status: 'Status', labels: 'Labels', search: 'Search...', noResults: 'No results', close: 'Close', bulkClose: 'Bulk Close', bulkLabel: 'Assign Label', export: 'Export', title: 'Detailed Data Table', rows: 'rows', page: 'Page', selectedCount: 'Selected', markDone: 'Mark as Done', exportCsv: 'Export CSV', appOnly: 'Changes are app-only, not synced to JIRA', selectAll: 'Select all', deselectAll: 'Deselect all', bulkLabelFor: 'Assign label to' },
  connect: { title: 'JIRA Connect', url: 'JIRA URL', token: 'API Token', projectKey: 'Project Key', assignee: 'Assignee Email', jql: 'JQL', connectBtn: 'Connect & Load', reConnect: 'Reconnect', connected: 'Connected', test: 'Test Connection', testError: 'Cannot connect', enterUrl: 'Please enter JIRA URL', enterToken: 'Please enter API Token', enterProject: 'Please enter Project Key', optional: 'optional' },
  projects: { title: 'Select Project', search: 'Search projects...', next: 'Continue', back: 'Back', loading: 'Loading projects...', error: 'Failed to load projects', noProjects: 'No projects found', switchProject: 'Change Project', step3: 'Step 3/4', connected: 'Connected: ', searchPlaceholder: 'Search projects by name or key...', project: 'projects', noMatch: 'No matching projects found.', enterHint: 'Press Enter to select' },
  query: { title: 'Query Config', assigneeLabel: 'Assignee Email', assigneePlaceholder: 'user@company.com', jqlLabel: 'JQL (optional)', jqlPlaceholder: 'e.g. status != Cancelled ORDER BY created DESC', start: 'Start Analysis', back: 'Back', step4: 'Step 4/4', notEntered: 'Not entered', emptyJql: 'Leave JQL empty to fetch all issues in the project.', skipAll: 'Skip, view all issues' },
  planner: { save: 'Save', logToJira: 'Log to JIRA', logged: 'Logged!', noTasks: 'No tasks yet', target: 'Target' },
  createTask: { title: 'Create Task', subtitle: 'Create a new issue in JIRA', projectKey: 'Project', issueType: 'Issue Type', summary: 'Summary', summaryPlaceholder: 'Enter task summary...', description: 'Description', descriptionPlaceholder: 'Enter description (optional)...', assignee: 'Assignee', assigneePlaceholder: 'user@company.com', sprint: 'Sprint', sprintPlaceholder: 'Enter Sprint name...', startDate: 'Start Date', dueDate: 'Due Date', estimate: 'Original Estimate (hours)', button: 'Create Task', creating: 'Creating...', success: 'Created successfully:' },
  ot: { otHours: 'OT Hours', leaveHours: 'Leave Hours', save: 'Save & Recalculate', effortFormula: 'Effort auto-calculated: (Workdays × 7 + OT - Leave) / Total estimated hours' },
  history: { title: 'History', save: 'Save Current', name: 'Snapshot Name', compare: 'Compare', delete: 'Delete', restore: 'Restore', storage: 'Storage', noSnapshots: 'No snapshots yet' },
  tabs: { overview: 'Overview', charts: 'Charts', data: 'Data', gantt: 'Gantt', compare: 'Compare', ot: 'OT & Leave', history: 'History' },
  common: { cancel: 'Cancel', delete: 'Delete', close: 'Close', loading: 'Loading...', error: 'Error', success: 'Success', overdue: 'unclosed tasks', viewTable: 'View Table', openMenu: 'Open menu', file: 'File', toggleTheme: 'Toggle theme', logout: 'Logout', retry: 'Retry', hours: 'hours', tasks: 'tasks', restore: 'Restore', deleteConfirm: 'Delete', back: 'Back' },
  lang: { vi: 'Tiếng Việt', en: 'English', switch: 'Switch Language' },
};
export default en;
